//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Snape
{
    using Microsoft.Xaml.Behaviors.Media;
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class SnakeRecordEntities1 : DbContext
        
    {
        private static SnakeRecordEntities1 _context;

        public SnakeRecordEntities1()
            : base("name=SnakeRecordEntities1")
        {
        }

        public static SnakeRecordEntities1 GetContext()
        {
            if (_context == null)
                _context = new SnakeRecordEntities1();
            return _context;
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<SnakeRecord> SnakeRecord { get; set; }

    }
    public class User
    {
        public string Name { get; set; }
        public int Score { get; set; }

        public User(string name, int score)
        {
            Name = name;
            Score = score;
        }

    }
}
