//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Snape
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class SnakeAntipovaEntities : DbContext
    {

        private static SnakeAntipovaEntities _context;
        public SnakeAntipovaEntities()
            : base("name=SnakeAntipovaEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Users> Users { get; set; }

        public static SnakeAntipovaEntities GetContext()
        {
            if (_context == null) _context = new SnakeAntipovaEntities();

            return _context;
        }
    }
}
